### ISSUE TITLE
Stolen Code From C0d3m4st4

### ISSUE THREAD

**Issue by Exeedy** [Keeperdy/PS4-Host-ESP8266-Firmware-for-5.05#1]
You have stolen the entire  code from C0d3m4st4 !****

**Comment by Keeperdy** [comment]
Have a look on Twitter, I prooved that it was just a stupid mistake!!! The matter is that if you use Arduino uploading sketch it does not erase the full flash, that why there are some traces of his code in my FW, because I tried his firmware and did not erased the full flash before uploading my sketch!!!

**Comment by Keeperdy** [comment]
Read README.MD

**Comment by c0d3m4st4** [comment]
Sorry for the hassle.

Now, i can confirm he didn't. As he explains if you flash an image and then upload your own sketch, traces of previous code remains in the sketch area. 

He prooved me i was wrong. 

I have deleted the accusing tweets and left a public apology to avoid further missunderstanding.

Sorry everyone, my fault :(
